### ISSUE TITLE
Email notifications to teams?

### ISSUE THREAD

**Issue by Nathan-tortoise** [galacticpuzzlehunt/gph-site#17]
Does this software have functionality for sending email to all teams? I've poked around and couldn't find anything on a first pass, but I'm sure I didn't look everywhere.

**Comment by cesium12** [comment]
No, it doesn't. For GPH, we use Mailgun for sending emails to individuals or single teams, but a separate mailing list service, Mailchimp, to email everyone. I believe the reason for this is that when mass-emailing it's very easy to get rate-limited or spam-blocked unless you use a service that is specifically designed for it, although I personally haven't dealt with that side of our operations so some of my teammates might know more. Regardless, the state of the codebase is that we have direct support for unicast emails, but for broadcasts we only provide some pages (like `/bridge`) that output lists of registered emails so that we can paste them into something external like Mailchimp. I don't know if we've looked into making this more automated, but it seems like (given that we already have a Mailchimp account set up, don't send mass emails very often, and do want to send manual tests to ourselves to sanity-check them) it hasn't been too much friction for us.

**Comment by Nathan-tortoise** [comment]
Ok, thanks for the info!
